include:
  - project: 'f1x1t/gitlab-ci'
    ref: master
    file: 'scheduled.yml'

smolensk15-nightly:
  extends: .scheduled-smolensk15

orel212-nightly:
  extends: .scheduled-orel212

bionic-nightly:
  extends: .scheduled-bionic

focal-nightly:
  extends: .scheduled-focal

elbrus-nightly:
  extends: .scheduled-elbrus

